[project]
name = "ez-career-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.1.40",
    "fastapi>=0.115.12",
    "google-api-core>=2.24.2",
    "langchain-openai>=0.3.1",
    "openai-agents>=0.0.9",
    "uvicorn[standard]>=0.34.1",
    "PyMuPDF>=1.25.0",
    "supabase>=2.15.0",
    "braintrust>=0.0.201",
    "weave>=0.51.44",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tool_agents"]
